import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { reviewApiPlugin, reviewRevision } from '../storybook/review-api.mjs';
import { flowReviewStore } from '../lib/flow-reviews.mjs';
test('local API enforces origin, JSON/header, methods, limits, revision and durable rejection', async t => {
  const directory = await fs.mkdtemp(path.join(os.tmpdir(), 'elma-flow-api-'));
  const store = flowReviewStore(path.join(directory, 'reviews.json'), { revision: 'test-revision' });
  let middleware;
  reviewApiPlugin('.', { store }).configureServer({ middlewares: { use: handler => { middleware = handler; } } });
  const server = http.createServer((req, res) => middleware(req, res, () => { res.writeHead(404); res.end(); }));
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  t.after(async () => { await new Promise(resolve => server.close(resolve)); assert.equal(path.dirname(directory), path.resolve(os.tmpdir())); assert.ok(path.basename(directory).startsWith('elma-flow-api-')); await fs.rm(directory, { recursive: true, force: true }); });
  const base = `http://127.0.0.1:${server.address().port}`;
  const route = base + '/__elma/reviews?flowId=investigation';
  const payload = { flowId: 'investigation', revision: 'test-revision', author: 'Аналитик', type: 'reject', text: 'Нужно уточнить правило', severity: 'must', phase: 'rules', category: 'behavior', stepId: 'observe' };
  const headers = { 'Content-Type': 'application/json', 'X-Elma-Review': '1', Origin: base };
  assert.equal((await fetch(route)).status, 200);
  assert.equal((await fetch(route, { headers: { Origin: 'https://outside.example' } })).status, 403);
  assert.equal((await fetch(route, { method: 'POST', body: JSON.stringify(payload), headers: { 'Content-Type': 'application/json' } })).status, 403);
  assert.equal((await fetch(route, { method: 'POST', body: JSON.stringify(payload), headers: { ...headers, Origin: 'https://outside.example' } })).status, 403);
  assert.equal((await fetch(route, { method: 'DELETE', headers })).status, 405);
  assert.equal((await fetch(route, { method: 'POST', body: '{', headers })).status, 400);
  assert.equal((await fetch(route, { method: 'POST', body: 'x'.repeat(20000), headers })).status, 400);
  assert.equal((await fetch(route, { method: 'POST', body: JSON.stringify({ ...payload, revision: 'old' }), headers })).status, 409);
  assert.equal((await fetch(route, { method: 'POST', body: JSON.stringify({ ...payload, flowId: 'upload' }), headers })).status, 400);
  const response = await fetch(route, { method: 'POST', body: JSON.stringify(payload), headers }); assert.equal(response.status, 201);
  const result = await response.json(); assert.equal(result.status, 'rejected');
  assert.equal((await fetch(route, { method: 'POST', body: JSON.stringify({ ...payload, type: 'approve' }), headers })).status, 409);
  assert.equal((await (await fetch(route)).json()).findings.length, 1);
  const status = await new Promise((resolve, reject) => { const req = http.request(base + '/__elma/reviews?flowId=investigation', { headers: { Host: 'outside.example' } }, res => { res.resume(); res.on('end', () => resolve(res.statusCode)); }); req.on('error', reject); req.end(); }); assert.equal(status, 403);
});
test('review fingerprint covers content and changes when business rules change', async t => {
  const directory = await fs.mkdtemp(path.join(os.tmpdir(), 'elma-flow-fingerprint-'));
  t.after(async () => { assert.equal(path.dirname(directory), path.resolve(os.tmpdir())); assert.ok(path.basename(directory).startsWith('elma-flow-fingerprint-')); await fs.rm(directory, { recursive: true, force: true }); });
  for (const folder of ['web/flows', 'storybook/stories', 'docs/workflows', 'lib']) await fs.mkdir(path.join(directory, folder), { recursive: true });
  for (const file of ['web/flows/catalog.js', 'storybook/stories/System.stories.js', 'docs/workflows/example.md', 'docs/STORYBOOK.md', 'docs/EXPERIENCE_REVIEW.md', 'lib/flow-reviews.mjs', 'storybook/review-api.mjs']) await fs.writeFile(path.join(directory, file), 'initial');
  const before = await reviewRevision(directory); assert.equal(before, await reviewRevision(directory));
  await fs.writeFile(path.join(directory, 'web/flows/catalog.js'), 'new business rule'); assert.notEqual(before, await reviewRevision(directory));
});
test('running review API accepts new catalog states without restarting and rejects old revision', async t => {
  const directory = await fs.mkdtemp(path.join(os.tmpdir(), 'elma-flow-hot-reload-'));
  for (const folder of ['web/flows', 'storybook/stories', 'docs/workflows', 'lib']) await fs.mkdir(path.join(directory, folder), { recursive: true });
  for (const file of ['docs/STORYBOOK.md', 'docs/EXPERIENCE_REVIEW.md', 'lib/flow-reviews.mjs', 'storybook/review-api.mjs']) await fs.writeFile(path.join(directory, file), 'fixture');
  const file = path.join(directory, 'web/flows/catalog.js');
  await fs.writeFile(path.join(directory, 'package.json'), JSON.stringify({ type: 'module' }));
  const writeCatalog = states => fs.writeFile(file, 'export const flowById = id => id === "live" ? ' + JSON.stringify({ id: 'live', initial: 'first', states: states.map(id => ({ id })) }) + ' : undefined;');
  await writeCatalog(['first']);
  let middleware;
  reviewApiPlugin(directory).configureServer({ middlewares: { use: handler => { middleware = handler; } } });
  const server = http.createServer((req, res) => middleware(req, res, () => { res.writeHead(404); res.end(); }));
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  t.after(async () => { await new Promise(resolve => server.close(resolve)); assert.equal(path.dirname(directory), path.resolve(os.tmpdir())); assert.ok(path.basename(directory).startsWith('elma-flow-hot-reload-')); await fs.rm(directory, { recursive: true, force: true }); });
  const url = `http://127.0.0.1:${server.address().port}/__elma/reviews?flowId=live`;
  const original = await (await fetch(url)).json();
  await writeCatalog(['first', 'added']);
  const latest = await (await fetch(url)).json(); assert.notEqual(latest.revision, original.revision);
  const payload = { flowId: 'live', stepId: 'added', revision: latest.revision, author: 'Analyst', type: 'comment', severity: 'should', phase: 'rules', category: 'behavior', text: 'Review the added state' };
  const post = value => fetch(url, { method: 'POST', headers: { 'X-Elma-Review': '1', 'Content-Type': 'application/json' }, body: JSON.stringify(value) });
  const result = await post(payload); assert.equal(result.status, 201); assert.equal((await result.json()).findings[0].stepId, 'added');
  assert.equal((await post({ ...payload, revision: original.revision })).status, 409);
});
