import { chromium } from 'playwright';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import assert from 'node:assert/strict';
import { createServer } from '../server.mjs';
import { fixture } from '../test/fixture.mjs';
import { articles } from '../dist/articles.js';

const directory = await fs.mkdtemp(path.join(os.tmpdir(), 'elma-wiki-browser-'));
const server = createServer({ directory, clientId: '', clientSecret: '', allowLocal: true });
await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
const base = `http://127.0.0.1:${server.address().port}`;
let browser;
try {
  browser = await chromium.launch({ headless: true, ...(process.env.BROWSER_CHANNEL ? { channel: process.env.BROWSER_CHANNEL } : {}) });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } }), errors = [], requests = [];
  page.on('pageerror', error => errors.push(error.message)); page.on('request', req => requests.push(req.url()));
  await fs.mkdir('qa', { recursive: true });
  await page.goto(base); await page.locator('#calc-total').waitFor();
  assert.equal((await page.locator('#calc-total').textContent()).replace(/\s/g, ' '), '24 000 ₽');
  await page.locator('#calc-percent').fill('50'); assert.equal((await page.locator('#calc-total').textContent()).replace(/\s/g, ' '), '48 000 ₽');
  await page.screenshot({ path: 'qa/service-desktop.png', fullPage: true });
  await page.goto(base + '/p/showcase/'); await page.locator('#main h1').waitFor();
  await page.goto(base + '/p/showcase/#/entities'); assert.equal(await page.locator('.entity-row').count(), 6);
  await page.goto(base + '/p/showcase/#/functions'); await page.locator('#main table tbody tr').first().waitFor();
  assert.equal(await page.locator('#main table tbody tr').count(), 5);
  for (const article of articles) { await page.goto(base + '/p/showcase/#/article/' + article.id); await page.waitForFunction(title => document.querySelector('#main h1')?.textContent === title, article.title); }
  await page.goto(base + '/login'); await page.locator('#local-login-card:not(.hidden)').waitFor();
  assert.equal(await page.locator('#github-login').getAttribute('href'), '/guide#oauth');
  await page.locator('#local-login').click(); await page.waitForURL(base + '/dashboard');
  await page.locator('#portal-name').fill('Учебный портал'); await page.locator('#create-portal button').click();
  await page.getByText('Портал создан.', { exact: false }).waitFor();
  const portal = await page.locator('#target-portal').inputValue(); assert.notEqual(portal, 'local');
  await page.locator('#config-files').setInputFiles({ name: 'example.e365', mimeType: 'application/octet-stream', buffer: await fixture() });
  await page.locator('#upload-config').click(); await page.locator('#upload-result a').waitFor();
  assert.ok((await page.locator('#upload-result').textContent()).includes('1 объектов'));
  await page.locator('#upload-result a').click(); await page.locator('#main h1').waitFor();
  await page.locator('#server-select').selectOption('development');
  await page.goto(base + `/p/${portal}/#/entities`); assert.equal(await page.locator('.entity-row').count(), 1);
  await page.locator('.entity-row').click(); await page.locator('[data-tab="functions"]').click();
  assert.equal(await page.locator('.function-grid').first().locator('.function-chip').count(), 2);
  await page.getByRole('button', { name: /Поиск по вики/ }).click(); await page.locator('#global-search').fill('onOpen');
  await page.locator('.search-result').filter({ hasText: 'example_module.records' }).first().waitFor();
  await page.keyboard.press('Escape');
  await page.goto(base + `/p/${portal}/#/dependency-map`); await page.locator('#main h1').waitFor();
  await page.goto(base + `/p/${portal}/#/comparison`); await page.locator('#filter-left').waitFor();
  await page.screenshot({ path: 'qa/personal-portal.png', fullPage: true });
  const other = await browser.newContext(), outsider = await other.newPage();
  const denied = await outsider.goto(base + `/p/${portal}/data.json`); assert.equal(denied.status(), 404); await other.close();
  await page.setViewportSize({ width: 390, height: 844 }); await page.goto(base);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await page.screenshot({ path: 'qa/service-mobile.png', fullPage: true });
  await page.goto(base + `/p/${portal}/#/overview`); await page.locator('#main h1').waitFor();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await page.getByRole('button', { name: 'Открыть меню' }).click();
  await page.locator('.sidebar').getByRole('link', { name: 'Загрузить конфигурацию', exact: true }).click();
  await page.locator('#import-files').waitFor();
  await page.locator('#import-files').setInputFiles({ name: 'update.e365', mimeType: 'application/octet-stream', buffer: await fixture({ fieldCode: 'updated_field' }) });
  await page.locator('[data-action="import-config"]').click(); await page.waitForFunction(() => document.querySelector('#import-result')?.textContent.includes('объектов'));
  await page.goto(base + `/p/${portal}/#/fields`); await page.locator('#main table tbody tr').first().waitFor();
  assert.ok((await page.locator('#main').textContent()).includes('updated_field'));
  assert.deepEqual(errors, []);
  assert.ok(requests.every(url => url.startsWith(base + '/')), 'No external requests during landing, showcase or local imports');
  console.log(JSON.stringify({ landing: true, estimator: true, showcase: true, articles: articles.length, localLogin: true, upload: true, update: true, search: true, ownerAccess: true, mobile: true, externalRequests: 0, pageErrors: errors }));
} finally {
  if (browser) await browser.close();
  await new Promise(resolve => server.close(resolve));
  assert.equal(path.dirname(directory), path.resolve(os.tmpdir()));
  assert.ok(path.basename(directory).startsWith('elma-wiki-browser-'));
  await fs.rm(directory, { recursive: true, force: true });
}
