import { chromium } from 'playwright';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import assert from 'node:assert/strict';
import { createServer } from '../server.mjs';
import { fixture } from '../test/fixture.mjs';
import { articles } from '../dist/articles.js';
import { loginEmail } from '../lib/email.mjs';
const directory=await fs.mkdtemp(path.join(os.tmpdir(),'e365-browser-test-'));
const messages=[];
const server=createServer({directory,allowLocal:false,sendEmail:async message=>messages.push(message)});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const base=`http://127.0.0.1:${server.address().port}`;
let browser;
try {
  browser=await chromium.launch({headless:true,...(process.env.BROWSER_CHANNEL?{channel:process.env.BROWSER_CHANNEL}:{})});
  const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],requests=[];
  page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));
  await fs.mkdir('qa',{recursive:true});
  await page.goto(base);await page.getByRole('link',{name:'Загрузить E365',exact:true}).waitFor();await page.screenshot({path:'qa/service-desktop.png',fullPage:true});
  await page.goto(base+'/p/showcase/');await page.getByRole('heading',{name:'Что нужно сделать?'}).waitFor();
  await page.goto(base+'/p/showcase/#/objects');assert.equal(await page.locator('.entity-row').count(),6);
  for (const article of articles) {await page.goto(base+'/p/showcase/#/article/'+article.id);await page.getByRole('heading',{name:article.title,exact:true}).waitFor();}
  await page.goto(base+'/login');assert.equal(await page.locator('#github-login').isDisabled(),true);
  await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.locator('#email').fill('person@example.org');await page.locator('#send-key').click();await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('Ключ отправлен'));
  await page.locator('#key').fill(messages.at(-1).key);await page.screenshot({path:'qa/email-login-mobile.png',fullPage:true});
  const emailPreview=await browser.newPage({viewport:{width:680,height:900}});
  await emailPreview.setContent(loginEmail(messages.at(-1)).html);await emailPreview.screenshot({path:'qa/email-preview.png',fullPage:true});await emailPreview.close();
  await page.locator('#verify-key').click();await page.waitForURL('**/workspaces');await page.goto(base+'/dashboard');await page.setViewportSize({width:1440,height:1000});
  await page.locator('#file').setInputFiles({name:'synthetic.e365',mimeType:'application/octet-stream',buffer:await fixture({secret:'<script>globalThis.pwned=true</script>'})});
  await page.getByRole('button',{name:'Создать проект из файла'}).click();await page.waitForURL(/\/p\/[0-9a-f-]{36}\/$/);
  const projectURL=page.url();await page.getByRole('heading',{name:'Что нужно сделать?'}).waitFor();
  await page.locator('a[href="#/task/field"]').click();await page.locator('#search').fill('title');await page.locator('.entity-row').first().click();
  await page.getByRole('button',{name:'Посмотреть исходный текст'}).click();await page.waitForFunction(()=>document.getElementById('preview').textContent.includes('globalThis.pwned'));
  assert.equal(await page.evaluate(()=>globalThis.pwned),undefined);
  await page.getByRole('link',{name:'← К результатам поиска'}).click();await page.locator('#search').waitFor();assert.equal(await page.locator('#search').inputValue(),'title');
  await page.getByRole('link',{name:/^Отчёт разбора/}).click();await page.locator('#reparse').waitFor();await page.locator('#summary').click();await page.locator('#diagnostic-summary:not(.hidden)').waitFor();
  const summary=await page.locator('#diagnostic-summary').textContent();assert.ok(!summary.includes('widgets/'));
  await page.locator('#reparse').click();await page.getByRole('heading',{name:'Отчёт разбора'}).waitFor();
  await page.getByRole('link',{name:'← Мои проекты',exact:true}).click();await page.locator('#projects .card').waitFor();
  await page.setViewportSize({width:390,height:844});await page.goto(projectURL);await page.getByRole('heading',{name:'Что нужно сделать?'}).waitFor();
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth));
  await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.tagName),'A');await page.screenshot({path:'qa/project-mobile.png',fullPage:true});
  await page.locator('a[href="#/task/field"]').focus();await page.keyboard.press('Enter');await page.locator('#search').waitFor();await page.locator('#search').focus();await page.keyboard.press('ControlOrMeta+A');await page.keyboard.type('title');assert.equal(await page.locator('.entity-row').count(),1);
  await page.goto(projectURL+'#/report');page.once('dialog',dialog=>dialog.accept());await page.locator('#delete').click();await page.waitForURL('**/dashboard');assert.equal(await page.locator('#projects .card').count(),0);
  assert.deepEqual(errors,[]);assert.ok(requests.every(url=>url.startsWith(base)),'No automatic outbound requests');
  console.log(`Browser: ${articles.length} guides; upload, task, search, source text, report, reparse, delete, mobile and keyboard passed.`);
} finally {
  if(browser)await browser.close();await new Promise(resolve=>server.close(resolve));
  assert.equal(path.dirname(directory),path.resolve(os.tmpdir()));assert.ok(path.basename(directory).startsWith('e365-browser-test-'));await fs.rm(directory,{recursive:true,force:true});
}
