import { mountSnapshotVisual } from '../../web/visual/render.js';
import { visualFixture } from '../../web/visual/fixtures.js';
export default {id:'solution-visual',title:'Решение/Процесс и форма',parameters:{layout:'fullscreen'}};
const story=state=>({render:()=>mountSnapshotVisual(visualFixture(state))});
export const Source = story('source');
export const Unknown = story('unknown');
export const Duplicate = story('duplicate');
export const Empty = story('empty');
export const Loading = story('loading');
export const Error = story('error');
export const Happy = {...story('happy'),parameters:{docs:{description:{story:'Проверенные переходы продолжают путь. Выбор шага мышью или клавиатурой начинает новый путь и сохраняет учебные значения; просмотр не создаёт вымышленный переход.'}}}};
export const Return = story('return');
export const MissingComment = story('missing-comment');
