import { mountExplanation } from '../../web/explanations/render.js';
import { explanationFixture, explanationFixtureActions } from '../../web/explanations/fixtures.js';
export default {id:'solution-explanation',title:'Решение/Объяснение',parameters:{layout:'fullscreen',docs:{description:{component:'Синтетические данные. Сохранение демонстрационное, без ELMA, AI-провайдера или записи в продукт.'}}}};
const story=state=>({render:()=>mountExplanation(explanationFixture(state),explanationFixtureActions())});
export const Ready=story('ready');
export const Draft=story('draft');
export const Saved=story('saved');
export const Stale=story('stale');
export const Loading=story('loading');
export const Error=story('error');
export const Conflict=story('conflict');
export const Historical=story('historical');
export const Regenerated=story('regenerated');
